### ISSUE TITLE
Correcting a few definitions to align with VIDO paper

### ISSUE THREAD

**Issue by sebastianduesing** [infectious-disease-ontology-extensions/VIDO#11]
A few definitions in the existing version of VIDO seem to have been updated since creation and need to be edited to align with the more recent definitions referred to in the forthcoming VIDO paper. I can submit a pull request to change these soon. For now, here's a list of the ones I found. The old definition is the one currently in the ontology, and the new definition is the one provided in the paper.

OBI: Organism
Old: Object that is an individual living system, such as animal, plant, bacteria or virus, that is capable of replicating or reproducing, growth and maintenance in the right environment. An organism may be unicellular or made up, like humans, of many billions of cells divided into specialized tissues and organs.
New: A material entity that is an individual living system, such as animal, plant, bacteria or virus, that is capable of replicating or reproducing, growth and maintenance in the right environment. An organism may be unicellular or made up, like humans, of many billions of cells divided into specialized tissues and organs.
* Note that this has also been moved from a subclass of object ot a subclass of material entity.

VIDO: Disordered virus
Old: Acellular structure having some arrangment of arrangment of viral components (e.g. viral capsid, viral DNA/RNA) that is clinically abnormal.
New: Acellular self-replicating organic structure having some clinically abnormal arrangement of viral components (e.g. viral capsid, viral DNA/RNA).

IDO: Pathogenic disposition
Old: Disposition borne by a material entity to establish localization in and result in formation of disorder in a host or immunocompetent members of the same species as the host.
New: Disposition borne by a material entity to establish localization in or produce toxins that can be transmitted to an organism or acellular structure, either of which may form disorder in the entity or immunocompetent members of the entity’s species.

IDO: Host role
Old: Role borne by an acellular structure containing a material entity other than the structure, or organism whose extended organism contains a material entity other than the organism, realized in use of that structure or organism as a site of reproduction or replication.
New: Role borne by either an organism whose extended organism contains a distinct material entity, or an acellular structure containing a distinct material entity, realized in use of that structure or organism as a site of reproduction or replication.

IDO: Pathogen host role
Old: Host role borne by an object having a pathogen as part or an borne by an organism having a pathogen as part of its extended organism.
New: Host role borne by an organism or acellular structure having a pathogen as part.

IDO: Infectious disorder
Old: Disorder that is part of an organism whose extended organism has some infectious agent or structure as part, which participates in the formation of infection.
New: Disorder that is part of an extended organism which has an infectious pathogen part, that exists as a result of a process of formation of disorder initiated by the infectious pathogen.

VIDO: Virus disorder
Old: Infectious disorder that exists as a result of a process of formation of disorder initiated by a virus or virus population.
New: Infectious disorder that exists as a result of a process of formation of disorder initiated by a virus.

Additionally, a few terms in the paper need to be added: viral disease incidence profile, viral disease incidence proportion profile, viral disease incidence rate profile, and viral dormancy interval. I can also submit a pull request for these.

**Comment by johnbeve** [comment]
Thank you @sebastianduesing, this is very helpful! Please do open a pull request to update the definitions and add the missing definitions, when you get a chance.
